[project]
authors = ["dylanli <dylan.h.li@outlook.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "AI_paper_collection_assistant"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"

[pypi-dependencies]
arxiv = ">=2.1.3, <3"
feedparser = ">=6.0.11, <7"
loguru = ">=0.7.3, <0.8"
instructor = ">=1.7.2, <2"
markitdown = ">=0.0.1a3, <0.0.1a4"
litellm = ">=1.57.5, <2"
retry = ">=0.9.2, <0.10"
slack-sdk = ">=3.34.0, <4"
flask = ">=3.1.0, <4"
markdown = ">=3.7, <4"
python-markdown-math = ">=0.8, <0.9"
